server:
  port: 8080

spring:
  application:
    name: api-gateway



  cloud:
    gateway:
      routes:
        - id: farmer-service
          uri: http://localhost:8081
          predicates:
            - Path=/farmer/**
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/order/**
        - id: payment-service
          uri: http://localhost:8083
          predicates:
            - Path=/payment/**
