server:
  port: 8080

#what is this code below for?
#It is used to configure the API Gateway to use JWT authentication with a JWK set URI.
#the JWK set URI is the endpoint where the JSON Web Key Set can be retrieved.
#for my application, I will use a placeholder URL.
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost/dummy
